#!/usr/bin/env bash
# john_hashcat_cheatsheet.sh
#
# Reference commands for cracking the sample hash files in ./samples/
# using John the Ripper and Hashcat, both pre-installed on Kali.
#
# This file is meant to be READ and run line-by-line, not executed top
# to bottom. Run: chmod +x john_hashcat_cheatsheet.sh, then copy/paste
# individual sections as you work through them.
#
# All target hashes were generated by scripts/05_generate_test_hashes.py
# against passwords WE chose - do not point these tools at hashes or
# accounts you don't own or have explicit authorization to test.

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SAMPLES="$PROJECT_DIR/samples"
WORDLIST="$PROJECT_DIR/wordlists/sample_wordlist.txt"
ROCKYOU="/usr/share/wordlists/rockyou.txt"   # gunzip -k /usr/share/wordlists/rockyou.txt.gz first

echo "=============================================================="
echo " 1. RAW MD5  -  samples/hashes_md5.txt"
echo "=============================================================="
echo "# John the Ripper (auto-detects format, but be explicit for practice):"
echo "john --format=Raw-MD5 --wordlist=$WORDLIST $SAMPLES/hashes_md5.txt"
echo "john --show --format=Raw-MD5 $SAMPLES/hashes_md5.txt   # view cracked results"
echo
echo "# Hashcat (mode 0 = MD5). Hashcat wants hash-only or hash:user format,"
echo "# so strip usernames first if needed:"
echo "cut -d: -f2 $SAMPLES/hashes_md5.txt > $SAMPLES/hashes_md5_only.txt"
echo "hashcat -m 0 -a 0 $SAMPLES/hashes_md5_only.txt $WORDLIST"
echo "hashcat -m 0 --show $SAMPLES/hashes_md5_only.txt"
echo

echo "=============================================================="
echo " 2. RAW SHA256  -  samples/hashes_sha256.txt"
echo "=============================================================="
echo "john --format=Raw-SHA256 --wordlist=$WORDLIST $SAMPLES/hashes_sha256.txt"
echo "cut -d: -f2 $SAMPLES/hashes_sha256.txt > $SAMPLES/hashes_sha256_only.txt"
echo "hashcat -m 1400 -a 0 $SAMPLES/hashes_sha256_only.txt $WORDLIST"
echo

echo "=============================================================="
echo " 3. LINUX SHA-512 CRYPT (shadow-file style)  -  samples/shadow_style.txt"
echo "=============================================================="
echo "# This is the real /etc/shadow format (\$6\$salt\$hash), good practice"
echo "# for realistic Linux password auditing scenarios."
echo "john --format=sha512crypt --wordlist=$WORDLIST $SAMPLES/shadow_style.txt"
echo "hashcat -m 1800 -a 0 $SAMPLES/shadow_style.txt $WORDLIST"
echo

echo "=============================================================="
echo " 4. BCRYPT  -  samples/hashes_bcrypt.txt"
echo "=============================================================="
echo "# Notice how much slower these are per-guess vs MD5/SHA256 above -"
echo "# that's the work factor from 04_slow_hash_demo.py in action."
echo "john --format=bcrypt --wordlist=$WORDLIST $SAMPLES/hashes_bcrypt.txt"
echo "hashcat -m 3200 -a 0 $SAMPLES/hashes_bcrypt.txt $WORDLIST"
echo

echo "=============================================================="
echo " 5. RULE-BASED ATTACKS (mangling, mirrors 03_dictionary_cracker.py)"
echo "=============================================================="
echo "# John's built-in mutation rules:"
echo "john --format=Raw-SHA256 --wordlist=$WORDLIST --rules $SAMPLES/hashes_sha256.txt"
echo
echo "# Hashcat with the classic 'best64' rule file (ships with Kali's hashcat):"
echo "hashcat -m 1400 -a 0 $SAMPLES/hashes_sha256_only.txt $WORDLIST -r /usr/share/hashcat/rules/best64.rule"
echo

echo "=============================================================="
echo " 6. BRUTE FORCE / MASK ATTACK (mirrors 02_bruteforce_cracker.py)"
echo "=============================================================="
echo "# Hashcat mask attack: 4 lowercase letters, e.g. to reproduce the"
echo "# 02_bruteforce_cracker.py demo target 'abcd' against its MD5 hash:"
echo "hashcat -m 0 -a 3 <target_hash> ?l?l?l?l"
echo
echo "# John incremental mode (brute force over a charset):"
echo "john --format=Raw-MD5 --incremental=Lower $SAMPLES/hashes_md5.txt"
echo

echo "=============================================================="
echo " 7. AGAINST A BIGGER, REALISTIC WORDLIST"
echo "=============================================================="
echo "# rockyou.txt is 14M real leaked passwords - the industry-standard"
echo "# wordlist. On Kali it usually needs unzipping first:"
echo "sudo gunzip -k $ROCKYOU.gz 2>/dev/null || true"
echo "john --format=Raw-MD5 --wordlist=$ROCKYOU $SAMPLES/hashes_md5.txt"
echo "hashcat -m 0 -a 0 $SAMPLES/hashes_md5_only.txt $ROCKYOU"
echo

echo "=============================================================="
echo " CHECKING YOUR RESULTS"
echo "=============================================================="
echo "diff <(john --show --format=Raw-MD5 $SAMPLES/hashes_md5.txt) $SAMPLES/ANSWER_KEY_do_not_peek.txt"
echo "# (formats differ slightly, this is just a sanity check - eyeball it)"
